# Generated by Django 2.2 on 2021-02-16 09:51

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('real_name', models.CharField(blank=True, max_length=10, null=True)),
                ('tz', timezone_field.fields.TimeZoneField(default='America/Los_Angeles')),
                ('activity_periods', models.ManyToManyField(blank=True, null=True, related_name='activity_periods', to='app.ActivityPeriod')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
