# Generated by Django 2.2 on 2021-02-16 10:11

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210216_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tz',
            field=timezone_field.fields.TimeZoneField(default='America/Los_Angeles', null=True),
        ),
    ]
