# Generated by Django 2.2 on 2021-02-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210216_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='tz',
        ),
    ]
