# Generated by Django 2.2 on 2021-02-16 10:20

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_member_tz'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tz',
            field=timezone_field.fields.TimeZoneField(default='Europe/London'),
        ),
    ]
