# Generated by Django 2.2 on 2021-02-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210216_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='real_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
